---
- hosts: 127.0.0.1
  tasks:
    - name: Copy the application files
      synchronize:
        src: app/main
        dest: ~/
    - name: Run
      shell: ~/main
      async: 2592000               # 60*60*24*30 – 1 month
      poll: 0
     


